AllCops:
  TargetRubyVersion:
    2.3.1

##############################################################################
#
# These *must* stay "false" because they will never work with ruumba:
# https://github.com/ericqweinstein/ruumba#fix-paths-and-unapplicable-cops
#
# Inapplicable Cops

Layout/AlignArguments:
  Enabled: false
Layout/AlignArray:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Layout/AlignParameters:
  Enabled: false
Layout/BlockAlignment:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/IndentFirstArgument:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/InitialIndentation:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/SpaceAfterComma:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideStringInterpolation:
  Enabled: false
Layout/TrailingBlankLines:
  Enabled: false

Lint/Void:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'app/views/layouts/mozilla-pdf-viewer.html.erb.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

##############################################################################
#
# Deviations from Defaults

Lint/AssignmentInCondition:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false

Style/EmptyElse:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Next:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/UnneededInterpolation:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
