require: rubocop-rspec
inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Include:
    - '**/*.rb'
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'fulcrum/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'ruumba/**/*'
    - 'solr/**/*'
    - 'tmp/**/*'
    - 'vagrant_scripts/**/*'
    - 'vendor/**/*'

Layout/AlignArray:
  Enabled: true

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/EmptyLinesAroundAccessModifier:
  EnforcedStyle: around

Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword

Lint/DuplicateMethods:
  Exclude:
  - 'app/presenters/e_pub_download_presenter.rb'
  - 'app/presenters/hyrax/file_set_presenter.rb'
  - 'lib/e_pub/chapter.rb'
  - 'lib/export/exporter.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Description: 'Avoid classes longer than 250 lines of code'
  Enabled: true
  Max: 250

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Vagrantfile'

Rails:
  Enabled: true

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/export/**/*'
    - 'lib/import/**/*'

Rails/TimeZone:
  Exclude:
  - 'app/services/counter_service.rb'
  - 'spec/**/*'

Rails/UnknownEnv:
  Environments:
  - production
  - development
  - test
  - cucumber

RSpec/AnyInstance:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/requests/**/*'
    - 'spec/routing/**/*'
    - 'spec/views/**/*'
    - 'lib/spec/integrations/**/*'
    - 'testing/spec/**/*'

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Style/InverseMethods:
  Enabled: true

Style/LineEndConcatenation:
  Exclude:
    - 'spec/test_app_templates/lib/generators/**/*'
    - 'lib/generators/**/*'

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false
