# Put any overides here
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/controllers/hyrax/monographs_controller_spec.rb'
    - 'spec/controllers/roles_controller_spec.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'config/initializers/mailboxer.rb'

Metrics/BlockLength:
  Enabled: true
  Max: 295 # default is 25

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/presenters/hyrax/file_set_presenter.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/riiif/file.rb'
    - 'app/services/downloads_controller_behavior.rb'
    - 'app/presenters/hyrax/monograph_presenter.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/helpers/press_helper.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/riiif/file.rb'
    - 'app/services/downloads_controller_behavior.rb'

Rails/Exit:
  Exclude:
    - 'lib/**/*'

Rails/OutputSafety:
  Exclude:
    - 'spec/presenters/concerns/title_presenter_spec.rb'
    - 'config/initializers/explain_partials.rb'
    - 'app/services/markdown_service.rb'
    - 'app/helpers/markdown_helper.rb'
    - 'app/helpers/gallery_helper.rb'
    - 'app/renderers/hyrax/renderers/attribute_renderer.rb'
    - 'app/renderers/hyrax/renderers/markdown_attribute_renderer.rb'
    - 'app/views/shared/_brand_press_footer_block_b.html.erb'

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/jobs/characterize_job_spec.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/actors/hyrax/monograph_actor_spec.rb'

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/EmptyLineAfterSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: true
  Max: 103 # default is 5

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/SubjectStub:
  Exclude:
    - 'spec/models/riiif/file_spec.rb'

RSpec/VerifiedDoubles:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'lib/import/importer.rb'
    - 'lib/import/csv_parser.rb'
    - 'spec/views/hyrax/file_sets/show.html.erb_spec.rb'
    - 'spec/views/hyrax/file_sets/_media.html.erb_spec.rb'
    - 'app/renderers/hyrax/renderers/*'
    - 'app/models/riiif/file.rb'
    - 'config/initializers/mailboxer.rb'

Style/GuardClause:
  Exclude:
    - 'lib/import/importer.rb'

Style/NumericLiterals:
  Exclude:
    - 'config/initializers/mailboxer.rb'

Style/RedundantReturn:
  Exclude:
    - 'app/presenters/concerns/analytics_presenter.rb'
