# Put any overides here

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/controllers/hyrax/monographs_controller_spec.rb'
    - 'spec/controllers/roles_controller_spec.rb'

Metrics/BlockLength:
  Enabled: true
  Max: 295 # default is 25

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/presenters/hyrax/file_set_presenter.rb'
    - 'lib/export/exporter.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/riiif/file.rb'
    - 'app/presenters/hyrax/monograph_presenter.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/helpers/press_helper.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/riiif/file.rb'

Naming/HeredocDelimiterCase:
  Exclude:
    - 'spec/lib/export/exporter_spec.rb'
    - 'spec/lib/import/importer_spec.rb'

Naming/HeredocDelimiterNaming:
  Exclude:
    - 'app/presenters/concerns/embed_code_presenter.rb'
    - 'app/presenters/concerns/social_share_widget_presenter.rb'
    - 'lib/spec/e_pub/bridge_to_webgl_spec.rb'
    - 'lib/spec/e_pub/cfi_spec.rb'
    - 'lib/spec/e_pub/chapter_spec.rb'
    - 'lib/spec/e_pub/chapter_presenter_spec.rb'
    - 'lib/spec/e_pub/snippet_spec.rb'
    - 'spec/presenters/concerns/embed_code_presenter_spec.rb'
    - 'spec/presenters/concerns/social_share_widget_presenter_spec.rb'

Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'app/forms/hyrax/forms/batch_upload_form.rb'
    - 'app/presenters/concerns/featured_representatives/file_set_presenter.rb'
    - 'app/presenters/concerns/featured_representatives/monograph_presenter.rb'
    - 'app/presenters/hyrax/file_set_presenter.rb'
    - 'app/presenters/hyrax/monograph_presenter.rb'

Performance/UnfreezeString:
  Exclude:
    - 'lib/export/exporter.rb'

Rails/Exit:
  Exclude:
    - 'lib/**/*'

Rails/HasManyOrHasOneDependent:
  Exclude:
    - 'app/models/component.rb'
    - 'app/models/lessee.rb'
    - 'app/models/press.rb'
    - 'app/models/product.rb'

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/breadcrumbs_helper.rb'
    - 'app/helpers/press_helper.rb'
    - 'app/helpers/banner_helper.rb'

Rails/InverseOf:
  Exclude:
    - 'app/models/press.rb'

Rails/OutputSafety:
  Exclude:
    - 'spec/presenters/concerns/title_presenter_spec.rb'
    - 'config/initializers/explain_partials.rb'
    - 'app/services/markdown_service.rb'
    - 'app/helpers/markdown_helper.rb'
    - 'app/helpers/gallery_helper.rb'
    - 'app/renderers/hyrax/renderers/attribute_renderer.rb'
    - 'app/renderers/hyrax/renderers/markdown_attribute_renderer.rb'
    - 'app/views/shared/_brand_press_footer_block_b.html.erb'

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/jobs/characterize_job_spec.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/actors/hyrax/monograph_actor_spec.rb'

RSpec/ExampleLength:
  Enabled: true
  Max: 103 # default is 5

RSpec/LetSetup:
  Exclude:
    - 'spec/actors/featured_representative_actor_spec.rb'
    - 'spec/controllers/e_pubs_controller_spec.rb'
    - 'spec/controllers/hyrax/monographs_controller_spec.rb'
    - 'spec/controllers/webgls_controller_spec.rb'
    - 'spec/controllers/webgls_controller_spec.rb'
    - 'spec/features/create_external_resource_spec.rb'
    - 'spec/features/file_set_cardinality_spec.rb'
    - 'spec/features/monograph_catalog_facets_spec.rb'
    - 'spec/features/press_catalog_spec.rb'
    - 'spec/features/show_monograph_spec.rb'
    - 'spec/features/sign_in_out_spec.rb'
    - 'spec/jobs/unpack_job_spec.rb'
    - 'spec/models/featured_representative_spec.rb'
    - 'spec/presenters/concerns/featured_representatives/file_set_presenter_spec.rb'
    - 'spec/presenters/e_pub_download_presenter.rb'
    - 'spec/presenters/hyrax/file_set_presenter_spec.rb'
    - 'spec/presenters/hyrax/monograph_presenter_spec.rb'
    - 'spec/system/toc_epub_chapter_spec.rb'
    - 'spec/views/monograph_catalog/index.html.erb_spec.rb'

RSpec/MessageSpies:
  Exclude:
    - 'spec/actors/create_with_import_files_actor_spec.rb'
    - 'spec/controllers/authentications_controller_spec.rb'
    - 'spec/controllers/e_pubs_controller_spec.rb'
    - 'spec/controllers/hyrax/file_sets_controller_spec.rb'
    - 'spec/controllers/hyrax/monographs_controller_spec.rb'
    - 'spec/controllers/jobs_controller_spec.rb'
    - 'spec/controllers/sessions_controller_spec.rb'
    - 'spec/jobs/attach_import_files_to_work_job_spec.rb'
    - 'spec/jobs/characterize_job_spec.rb'
    - 'spec/jobs/create_derivatives_job_spec.rb'
    - 'spec/jobs/curation_concern_update_index_job_spec.rb'
    - 'spec/hydra-derivatives/processors/video_spec.rb'
    - 'spec/jobs/hyrax/grant_read_to_members_job_spec.rb'
    - 'spec/jobs/hyrax/revoke_edit_from_members_job_spec.rb'
    - 'spec/jobs/hyrax/grant_edit_to_members_job_spec.rb'
    - 'spec/lib/devise/http_header_authenticatable_spec.rb'
    - 'spec/lib/devise/keycard_authenticatable_spec.rb'
    - 'spec/models/riiif/file_spec.rb'
    - 'spec/services/analytics_service_spec.rb'

RSpec/SubjectStub:
  Exclude:
    - 'spec/hydra-derivatives/processors/video_spec.rb'
    - 'spec/models/riiif/file_spec.rb'

Style/CommentedKeyword:
  Exclude:
    - 'spec/controllers/hyrax/monographs_controller_spec.rb'
    - 'spec/controllers/monograph_catalog_controller_spec.rb'
    - 'spec/features/press_catalog_spec.rb'
    - 'spec/presenters/hyrax/monograph_presenter_spec.rb'
    - 'spec/requests/api/v1/component_products_spec.rb'
    - 'spec/requests/api/v1/lessee_products_spec.rb'
    - 'spec/requests/api/v1/product_components_spec.rb'
    - 'spec/requests/api/v1/product_lessees_spec.rb'
    - 'spec/views/shared/_my_actions.html.erb_spec.rb'

Style/DateTime:
  Exclude:
    - 'app/presenters/concerns/cc_analytics_presenter.rb'
    - 'app/services/counter_service.rb'
    - 'app/services/unpack_service.rb'
    - 'spec/factories/monographs.rb'
    - 'spec/features/press_catalog_spec.rb'
    - 'spec/features/press_catalog_sort_spec.rb'
    - 'spec/models/monograph_spec.rb'
    - 'spec/presenters/concerns/cc_analytics_presenter_spec.rb'
    - 'spec/views/monograph_catalog/index.html.erb_spec.rb'

Style/EvalWithLocation:
  Exclude:
    - 'app/services/analytics_service.rb'
    - 'spec/presenters/hyrax/monograph_presenter_spec.rb'
    - 'spec/views/monograph_catalog/index.html.erb_spec.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'lib/import/importer.rb'
    - 'lib/import/csv_parser.rb'
    - 'spec/views/hyrax/file_sets/show.html.erb_spec.rb'
    - 'spec/views/hyrax/file_sets/_media.html.erb_spec.rb'
    - 'app/renderers/hyrax/renderers/*'
    - 'app/models/riiif/file.rb'
    - 'config/initializers/mailboxer.rb'

Style/GuardClause:
  Exclude:
    - 'lib/import/importer.rb'

Style/NumericLiterals:
  Exclude:
    - 'config/initializers/mailboxer.rb'

Style/RedundantReturn:
  Exclude:
    - 'app/presenters/concerns/analytics_presenter.rb'
