services:
  db:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: helio-admin
      MYSQL_USER: helio
      MYSQL_PASSWORD: helio
      MYSQL_DATABASE: heliotrope_development
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    networks:
      - heliotrope

  solr:
    image: solr:8-slim
    ports:
      - "8983:8983"
    environment:
      - SOLR_JAVA_MEM=-Xms1024m -Xmx1024m
      - SOLR_HEAP=1024m
    volumes:
      - ./solr/config:/opt/solr/server/solr/configsets/fulcrum-dev
      - solr-data:/var/solr
    networks:
      - heliotrope

  fcrepo:
    image: ghcr.io/samvera/fcrepo4:4.7.5@sha256:83fbdb371402e9fcd1e8a055ea1d61a5e84ae6c3c229fccb0965ad6f434d94d2
    volumes:
      - fcrepo-data:/data
    ports:
      - 8080:8080
    networks:
      - heliotrope

  redis:
    image: redis:6-bookworm
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - heliotrope

  resque:
    depends_on:
      - app
      - db
      - solr
      - redis
      - fcrepo
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_USER: helio
      MYSQL_PASSWORD: helio
      MYSQL_DATABASE: heliotrope_development
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      RAILS_ENV: development
    volumes:
      - .:/app
      - gem_cache:/gems
      - node_modules:/app/node_modules
    healthcheck:
      disable: true
    stop_signal: SIGQUIT
    command: >
      sh -c "bin/setup && 
             bundle exec rake resque:pool"
    networks:
      - heliotrope

  app:
    depends_on:
      - db
      - solr
      - redis
      - fcrepo
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/gems
      - node_modules:/app/node_modules
    restart: always
    environment:
      MYSQL_USER: helio
      MYSQL_PASSWORD: helio
      MYSQL_DATABASE: heliotrope_development
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      RAILS_ENV: development
      CHECKPOINT_DATABASE_URL: 'sqlite://db/checkpoint-development.sqlite3'
      KEYCARD_DATABASE_URL: 'sqlite://db/keycard-development.sqlite3'
      SOLR_URL: http://solr:8983
      FEDORA_URL: http://fcrepo:8080
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: >
      sh -c "chmod +x entrypoints/docker-app.sh &&
            ./entrypoints/docker-app.sh &&
            bin/rails s -b 0.0.0.0"
    networks:
      - heliotrope

volumes:
  gem_cache:
  node_modules:
  db-data:
    driver: local
  fcrepo-data:
  solr-data:
  redis-data:

networks:
  heliotrope:
    driver: bridge
