#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require 'ostruct'

options = OpenStruct.new
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: export [--file <filename>] <monograph_id>"
  opts.on('-f', '--file [FILENAME]', 'Name of output file') do |filename|
    options.file = filename
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    puts opts
    exit 0
  end
end
option_parser.parse!(ARGV)

if ARGV.empty?
  puts option_parser.help
else
  require File.expand_path('../config/environment', __dir__)
  require 'export'
  monograph_id = ARGV[0]
  $stdout.reopen(options.file, 'w') if options.file
  begin
    puts Export::Exporter.new(monograph_id).export
  rescue StandardError => e
    STDERR.puts e.message
  end
end
