#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require 'ostruct'
require_relative 'api/lackey'

list_products = false
list_lessees = false

options = OpenStruct.new
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{$PROGRAM_NAME} -l -p [-b <base_uri>] <token>"
  opts.on('-b', '--base [uri]', 'URL to api') do |base_uri|
    # def self.normalize_base_uri(url) #:nodoc:
    #   normalized_url = url.dup
    #   use_ssl = (normalized_url =~ /^https/) || (normalized_url =~ /:443\b/)
    #   ends_with_slash = normalized_url =~ /\/$/
    #
    #   normalized_url.chop! if ends_with_slash
    #     #   normalized_url.gsub!(/^https?:\/\//i, '')
    #     #
    #     #   "http#{'s' if use_ssl}://#{normalized_url}"
    #     # end
    #     # options.base_uri = HTTParty.normalize_base_uri(base_uri)
    options.base_uri = base_uri
  end
  opts.on('-p', '--products', 'List products') do
    list_products = true
  end
  opts.on('-l', '--lessees', 'List lessees') do
    list_lessees = true
  end
  opts.on_tail('-h', '--help', 'Print this help message') do
    puts opts
    exit 0
  end
end
option_parser.parse!(ARGV)

if ARGV.empty?
  puts option_parser.help
else
  begin
    Lackey.default_options[:base_uri] = options.base_uri if options.base_uri
    Lackey.default_options[:headers][:authorization] = "Bearer #{ARGV[0]}"
    puts Lackey.default_options
    lackey = Lackey.new
    puts lackey.products if list_products
    puts lackey.lessees if list_lessees
  rescue StandardError => e
    STDERR.puts e.message
  end
  exit!(0)
end
