# Generated by curation_concerns:models:install
class FileSet < ActiveFedora::Base
  include ::CurationConcerns::FileSetBehavior
  include ::CurationConcerns::BasicMetadata
  include GlobalID::Identification

  property :caption, predicate: ::RDF::Vocab::SCHEMA.caption do |index|
    index.as :stored_searchable
  end
  property :alt_text, predicate: ::RDF::Vocab::SCHEMA.accessibilityFeature do |index|
    index.as :stored_searchable
  end
  property :content_type, predicate: ::RDF::Vocab::SCHEMA.contentType do |index|
    index.as :stored_searchable
  end
  property :keywords, predicate: ::RDF::Vocab::DC.subject do |index|
    index.as :stored_searchable
  end
  property :relation, predicate: ::RDF::Vocab::DC.relation do |index|
    index.as :stored_searchable
  end
  property :identifier, predicate: ::RDF::Vocab::DC.identifier do |index|
    index.as :stored_searchable
  end
  property :copyright_holder, predicate: ::RDF::Vocab::SCHEMA.copyrightHolder do |index|
    index.as :stored_searchable
  end
  property :date_published, predicate: ::RDF::Vocab::SCHEMA.datePublished do |index|
    index.as :stored_searchable
  end
  property :external_resource, predicate: ::RDF::Vocab::DC.source do |index|
    index.as :symbol
  end
  property :persistent_id, predicate: ::RDF::Vocab::DC.URI do |index|
    index.as :symbol
  end
end
